spring:
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jeepaydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: TGLOCAL(dRmvFH1+ZfqENVprcmQ/3A==)
      password: TGLOCAL(u8+rFyL8AMAbhqriFQg1n3pVDKWlF/9k)
      druid: #以下均为默认值
        # 配置测试查询语句 orcle:select 1 from dual   sqlserver  mysql SELECT 1
        validationQuery: select 1 from dual
        # 初始化大小，最小，最大
        initialSize: 10
        minIdle: 10
        maxActive: 200
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 180000
        testOnBorrow: false
        testWhileIdle: true
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: config,stat,wall
        #合并多个DruidDatasource的监控数据
        useGlobalDataSourceStat: true
        #通过connectProperties属性来打开mergesql功能罗慢sQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;




